steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/rooms-qr-generator/rooms-qr-generator:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/rooms-qr-generator/rooms-qr-generator:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - rooms-qr-generator
      - --image
      - gcr.io/rooms-qr-generator/rooms-qr-generator:$SHORT_SHA
      - --project
      - rooms-qr-generator
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - GOOGLE_SERVICE_ACCOUNT_JSON=google-service-account-json:latest

images:
  - gcr.io/rooms-qr-generator/rooms-qr-generator:$SHORT_SHA
